GET http://localhost:5000/

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyLWM3NWRwcFFySWwiLCJuYW1lIjoiZGltYXMiLCJ1c2VyRW1haWwiOiJkaW1hc0BnbWFpbC5jb20iLCJpYXQiOjE2ODUwODAxMjcsImV4cCI6MTY4NTA4NzMyN30.7FK_EQrrag081urO2GPm8EMOGM8IDJeAtBNTvuBPlzU

###
GET  http://localhost:5000/users/user-nEDmB38XF9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyLW5FRG1CMzhYRjQiLCJuYW1lIjoiZGltYXMiLCJ1c2VyRW1haWwiOiJkaW1hc0BnbWFpbC5jb20iLCJpYXQiOjE2ODQ4MzU3MDksImV4cCI6MTY4NDg0MjkwOX0.Ihjzr65Z_2S90g0pMZSVuyiULaBfhpaWbcdYNHTuCII

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "mama",
    "email": "mama@gmail.com",
    "password": "12345678"
}

###
PUT http://localhost:5000/ubahPassword/:id
Authorization: Bearer 
Content-Type: application/json

{
    "currentPass": "",
    "newPass": "",
    "confPass": "",
}


###
PUT http://localhost:5000/editUser/:id
Authorization: Bearer 
Content-Type: application/json

{
    "name": "",
    "email": "",
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "mama@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:5000/token

###
GET http://localhost:5000/makanan
Authorization: Bearer 

###
GET http://localhost:5000/makanan/food-uZ08wgf5Gp
Authorization: Bearer 

###
POST http://localhost:5000/makanan/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyLXlodFNpdjlrRGEiLCJuYW1lIjoibWFtYSIsInVzZXJFbWFpbCI6Im1hbWFAZ21haWwuY29tIiwiaWF0IjoxNjg1MzM0NDQ3LCJleHAiOjE2ODUzNDE2NDd9.NBqFP_-zlMAKJif0AmgN2jFG3UJ8MokYwSPcuLyVaJs
Content-Type: application/json

{    
    "name_food": "Oatmeal Instan (100 g)",
    "kalori": "91",
    "protein": "2.46",
    "lemak": "1.2",
    "sodium": "122",
    "link_nutrisi": "https://www.fatsecret.co.id/kalori-gizi/umum/oatmeal-instan?portionid=53170&portionamount=100,000",
    "link_resep": "https://www.sehatq.com/review/variasi-resep-oatmeal-antibosan-untuk-turunkan-berat-badan",
    "ManisAsin": "Manis",
    "KuahKering": "Kering",
    "PedasTidak": "Tidak Pedas",
    "TipeMakananVSD": "Vegetarian",
    "HalalHaram": "Halal"
}

###
DELETE http://localhost:5000/logout
